---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---


```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)

library(flexdashboard)
```

```{r}
data("instacart")

fresh_fruits = instacart %>% 
  filter(aisle == "fresh fruits") %>% 
  count(product_name) %>% 
  filter(n>2500) %>% 
  arrange(desc(n)) %>% 
  mutate(percent = n / sum(n) * 100)
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
instacart %>% 
  count(aisle) %>% 
  filter(n > 5000) %>% 
  mutate(aisle = factor(aisle),
         aisle = fct_reorder(aisle, n)) %>% 
  plot_ly(
    x = ~aisle, y = ~n, color = ~aisle, 
    type = "bar", colors = "viridis") %>% 
  layout(
    xaxis = list(title = FALSE),
    yaxis = list(title = "Count"),
    title = "Aisles with more than 5000 items ordered"
  )
```


Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
fresh_fruits %>% 
  plot_ly(labels = ~product_name, values = ~percent, type = 'pie') %>% 
  layout(title = '15 most popular fruits consumption by categories',
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
```

### Chart C

```{r}
instacart %>% 
  filter(aisle == "fresh fruits") %>% 
  filter(product_name %in% c("Banana", "Bag of Organic Bananas", "Organic Strawberries", "Large Lemon", "Organic Avocado", "Organic Hass Avocado", "Strawberries", "Lims", "Honeycrisp Apple")) %>%  
  plot_ly(
    y = ~order_hour_of_day, x = ~product_name, color = ~product_name, 
    type = "box", colors = "viridis") %>%
  layout(
    xaxis = list(title = FALSE),
    yaxis = list(title = "Order-hour of the day"),
    title = "Order hour distribution of 8 most popular fruits")
```


